#!/bin/python3
from string import Template

USELESS='I_AM_USELESS'
CODE="#!/bin/python3\nfrom string import Template\n\nUSELESS='I_AM_USELESS'\nCODE=$repr_code\nMAIN='code_template = Template(CODE)\\nwith open(\\'Grace_kid\\', \\'w\\') as kid_file:\\n    kid_file.write(code_template.substitute(repr_code=repr(CODE)))'\n\n# Hello I am a comment\n\nexec(MAIN)\n"
MAIN='code_template = Template(CODE)\nwith open(\'Grace_kid\', \'w\') as kid_file:\n    kid_file.write(code_template.substitute(repr_code=repr(CODE)))'

# Hello I am a comment

exec(MAIN)
